// translations.js (приклад)

const translations = {
    uk: {
        pageTitle: "ВОЛЯ — Епічна Історична Гра",
        mainHeading: "ВОЛЯ",
        heroTagline: "Епічна подорож крізь тисячоліття боротьби за свободу.",
        // ... існуючі переклади ...

        aboutGameTitle: "Про гру \"ВОЛЯ\"",
        aboutGameParagraph1: "\"ВОЛЯ\" — це епічна історична гра, яка запрошує вас пережити тисячоліття боротьби українського народу за свою свободу. Це не просто подорож крізь віки, а глибоке дослідження стійкості духу, що передається з покоління в покоління.",
        aboutGameParagraph2: "Ми створюємо \"ВОЛЮ\" за модульним принципом, що дозволяє нам постійно розвивати гру, розширювати її світи та додавати унікальні механіки, спираючись на ваші відгуки.",
        modularPrincipleHighlight: "модульним принципом", // Окремий переклад для виділеного тексту
        aboutGameParagraph3: "Ваша подорож почнеться в епоху Скіфів – могутнього та загадкового народу степів. Цей перший модуль, доступний як самостійна гра, занурить вас у лінійний, але масштабний сюжет, де кожен крок має значення у боротьбі за виживання та незалежність.",
        scythiansIntroHighlight: "Ваша подорож почнеться в епоху Скіфів",
        aboutGameParagraph4: "Далі ми відкриємо для вас інші, не менш захопливі сторінки історії: від давніх слов'ян до доби Київської Русі, від козацьких повстань до трагічних подій XX століття та героїчного сьогодення. Кожна епоха — це докорінно інший ігровий світ, що пропонує унікальний геймплей, виклики та можливості.",
        aboutGameParagraph5: "Ключова особливість \"ВОЛІ\" — це механіка інтелектуальних діалогів, що розвивається, та концепція \"Волі\", внутрішньої сили, що впливає на увесь ігровий процес. Взаємодійте з історичними персонажами, приймайте складні рішення, і пам'ятайте: кожен ваш вибір, кожне сказане слово або дія, накопичуватиме \"Волю\", що у фіналі визначить долю всього народу. Ваші дії в минулому змінять майбутнє, ведучи до однієї з кількох захопливих кінцівок, включаючи особливо складний, але довгоочікуваний щасливий фінал.",
        aiDialoguesHighlight: "Ключова особливість \"ВОЛІ\" — це механіка інтелектуальних діалогів",
        volyaConceptHighlight: "\"Волі\"",
        happyEndingHighlight: "особливо складний, але довгоочікуваний щасливий фінал",
        aboutGameParagraph6: "Ми віримо в \"живий канон\": гра буде постійно оновлюватися та вдосконалюватися. Ваші улюблені персонажі можуть розвиватися, а сюжетні лінії – поглиблюватися чи навіть переосмислюватися, щоб забезпечити максимально захопливий та історично-відчутний досвід. Кожна нова версія гри, яку ми випустимо, буде вважатися канонічною.",
        livingCanonHighlight: "\"живий канон\"",
        finalVersionCanonicalHighlight: "Кожна нова версія гри, яку ми випустимо, буде вважатися канонічною.",
        aboutGameCallToAction: "Приєднуйтесь до \"ВОЛІ\" і станьте частиною великої історії!",
        joinVolyaHighlight: "Приєднуйтесь до \"ВОЛІ\" і станьте частиною великої історії!",

        // ... інші переклади ...
        olesBackstoryPageTitle: "Передісторія Олеся — ВОЛЯ",
        olesBackstoryMainHeading: "Передісторія Олеся",
        olesBackstoryHeroTagline: "Сучасний воїн, що несе на собі тисячоліття боротьби за Волю.",
        olesBackstorySectionTitle: "Гартований Воїн Сучасності",
        olesBackstoryBirthDateLabel: "Дата народження:",
        olesBackstoryBirthDateValue: "Приблизно 2000 рік.",
        olesBackstoryChildhoodHeading: "Дитинство та Юність (2000-2022):",
        olesBackstoryChildhoodText: "Олесь народився і виріс у звичайній українській родині. Це була типова проукраїнська сім'я, яка глибоко цінувала свою історію, мову, культуру та традиції. Його виховували на принципах патріотизму, поваги до старших та любові до рідної землі. У дитинстві Олесь був активним і допитливим хлопцем, захоплювався спортом та історією, особливо козацькою добою. Він ріс у світі відносної стабільності, мріяв про звичайне життя, можливо, пов'язане з інженерією або ІТ – тим, що давало б конкретний результат і покращувало життя. Він не був військовим за покликом, але цінності, закладені родиною, сформували його характер – відповідальний, наполегливий, з почуттям справедливості.",
        olesBackstoryWarBeginningHeading: "Початок Війни та Шлях Воїна (2022):",
        olesBackstoryWarBeginningText: "Коли в лютому 2022 року розпочалося повномасштабне вторгнення, життя Олеся, як і мільйонів українців, змінилося назавжди. Без вагань, одразу після перших ударів, він пішов добровольцем до військкомату. Його мотивація була кришталево чистою – захистити свій дім, свою родину, свою країну від ворога, який прагнув знищити все, що він любив. Початкова підготовка була інтенсивною, але Олесь, завдяки своїй фізичній формі та внутрішній зібраності, швидко адаптувався до суворих реалій.",
        olesBackstoryWarHardeningHeading: "Загартування Вогнем (2022-2030):",
        olesBackstoryWarHardeningText1: "Протягом восьми років війни, до 2030 року, Олесь пройшов шлях від новобранця до справді професійного та прожореного воїна. Він бачив на власні очі пекло найжорстокіших битв, втрачав побратимів, переживав найважчі обстріли та окопну війну. Його шлях проліг через оборону Києва, кровопролитні бої на сході, контрнаступи та місяці виснажливого протистояння.",
        olesBackstoryWarHardeningHighlight1: "професійного та прожореного воїна",
        olesBackstoryWarHardeningText2: "Його спеціалізацією стала розвідка та штурмові операції – він був там, де потрібно було проникнути найглибше в тил ворога або прорвати найміцнішу оборону. Олесь навчився мислити нестандартно, приймати миттєві рішення під шаленим тиском, а його навички виживання та бою в найскладніших умовах стали легендарними серед побратимів. Його внутрішній світ, хоч і був загартований і посірілий від війни, ніколи не втрачав тієї іскри \"Волі\" – незламної віри у перемогу та готовності йти до кінця. Він став живим втіленням козацького духу – не тільки через бойові навички, а й через внутрішню свободу, непокору та вірність своїй землі.",
        olesBackstoryWarHardeningHighlight2: "розвідка та штурмові операції",
        olesBackstoryFinalBattleHeading: "Напередодні Фінального Бою (2030, Мар'їнка):",
        olesBackstoryFinalBattleText: "До 2030 року, коли Україна розпочала свій вирішальний наступ, Олесь став одним з найдосвідченіших і найцінніших бійців. Він мав звання, повагу командирів та негласне лідерство серед своїх. Біль, втома та численні шрами були частиною його сутності, але його очі горіли тією ж рішучістю, що й на початку, лише тепер до неї додалася глибина знання ціни боротьби. Він перебував у Мар'їнці, на передовій українського наступу, готовий до фінального, вирішального бою за Донбас. Саме тут, у цьому історичному і символічному місці, йому судилося зіткнутися не лише з останніми викликами війни, а й з покликом тисячолітньої \"Волі\" своїх предків, що має проявитися в критичний момент.",
        olesBackstoryBackButton: "← Повернутися до головної сторінки",
        footerText: "&copy; 2025 Проєкт \"ВОЛЯ\". Всі права захищені.",
    },
    en: {
        pageTitle: "VOLYA — Epic Historical Game",
        mainHeading: "VOLYA",
        heroTagline: "An epic journey through a millennium of struggle for freedom.",
        // ... existing translations ...

        aboutGameTitle: "About \"VOLYA\" Game",
        aboutGameParagraph1: "\"VOLYA\" is an epic historical game that invites you to experience a millennium of the Ukrainian people's struggle for their freedom. This is not just a journey through the ages, but a deep exploration of the resilience of spirit passed down from generation to generation.",
        aboutGameParagraph2: "We are creating \"VOLYA\" on a modular principle, allowing us to constantly develop the game, expand its worlds, and add unique mechanics, based on your feedback.",
        modularPrincipleHighlight: "modular principle",
        aboutGameParagraph3: "Your journey will begin in the Scythian era – a mighty and mysterious people of the steppes. This first module, available as a standalone game, will immerse you in a linear but large-scale story where every step matters in the struggle for survival and independence.",
        scythiansIntroHighlight: "Your journey will begin in the Scythian era",
        aboutGameParagraph4: "Next, we will open other equally exciting pages of history for you: from ancient Slavs to the era of Kyivan Rus', from Cossack uprisings to the tragic events of the XX century and the heroic present. Each era is a fundamentally different game world, offering unique gameplay, challenges, and opportunities.",
        aboutGameParagraph5: "A key feature of \"VOLYA\" is the evolving intelligent dialogue mechanic and the concept of \"Volya\" (Will/Freedom), an inner force that influences the entire gameplay. Interact with historical figures, make difficult decisions, and remember: every choice you make, every word spoken or action taken, will accumulate \"Volya\", which will ultimately determine the fate of the entire nation. Your actions in the past will change the future, leading to one of several captivating endings, including a particularly challenging but long-awaited happy ending.",
        aiDialoguesHighlight: "A key feature of \"VOLYA\" is the evolving intelligent dialogue mechanic",
        volyaConceptHighlight: "\"Volya\" (Will/Freedom)",
        happyEndingHighlight: "a particularly challenging but long-awaited happy ending",
        aboutGameParagraph6: "We believe in a \"living canon\": the game will be constantly updated and improved. Your favorite characters may evolve, and storylines may be deepened or even re-imagined to ensure the most engaging and historically immersive experience. Every new version of the game we release will be considered canonical.",
        livingCanonHighlight: "\"living canon\"",
        finalVersionCanonicalHighlight: "Every new version of the game we release will be considered canonical.",
        aboutGameCallToAction: "Join \"VOLYA\" and become part of a great history!",
        joinVolyaHighlight: "Join \"VOLYA\" and become part of a great history!",

        // ... other translations ...
        olesBackstoryPageTitle: "Oles' Backstory — VOLYA",
        olesBackstoryMainHeading: "Oles' Backstory",
        olesBackstoryHeroTagline: "A modern warrior carrying a millennium of struggle for Freedom.",
        olesBackstorySectionTitle: "A Warrior Hardened by Modernity",
        olesBackstoryBirthDateLabel: "Date of Birth:",
        olesBackstoryBirthDateValue: "Circa 2000.",
        olesBackstoryChildhoodHeading: "Childhood and Youth (2000-2022):",
        olesBackstoryChildhoodText: "Oles was born and raised in an ordinary Ukrainian family. It was a typical pro-Ukrainian family that deeply valued its history, language, culture, and traditions. He was brought up on principles of patriotism, respect for elders, and love for his homeland. In his childhood, Oles was an active and curious boy, fond of sports and history, especially the Cossack era. He grew up in a world of relative stability, dreaming of a normal life, perhaps related to engineering or IT – something that would bring tangible results and improve life. He wasn't a soldier by calling, but the values instilled by his family shaped his character – responsible, persistent, with a sense of justice.",
        olesBackstoryWarBeginningHeading: "Beginning of the War and the Warrior's Path (2022):",
        olesBackstoryWarBeginningText: "When the full-scale invasion began in February 2022, Oles's life, like millions of Ukrainians, changed forever. Without hesitation, immediately after the first strikes, he volunteered at the military enlistment office. His motivation was crystal clear – to protect his home, his family, his country from an enemy who sought to destroy everything he loved. Initial training was intensive, but Oles, thanks to his physical fitness and inner composure, quickly adapted to the harsh realities.",
        olesBackstoryWarHardeningHeading: "Hardened by Fire (2022-2030):",
        olesBackstoryWarHardeningText1: "Over eight years of war, by 2030, Oles transformed from a recruit into a truly professional and seasoned warrior. He witnessed firsthand the hell of the fiercest battles, lost comrades, endured the heaviest shelling and trench warfare. His path led through the defense of Kyiv, bloody battles in the east, counteroffensives, and months of exhausting confrontation.",
        olesBackstoryWarHardeningHighlight1: "professional and seasoned warrior",
        olesBackstoryWarHardeningText2: "His specialization became reconnaissance and assault operations – he was where it was necessary to penetrate deepest into enemy lines or break through the strongest defenses. Oles learned to think outside the box, make instant decisions under immense pressure, and his survival and combat skills in the most difficult conditions became legendary among his comrades. His inner world, though hardened and grayed by war, never lost that spark of \"Volya\" – an unbreakable faith in victory and a readiness to go to the end. He became a living embodiment of the Cossack spirit – not only through his combat skills, but also through his inner freedom, defiance, and loyalty to his land.",
        olesBackstoryWarHardeningHighlight2: "reconnaissance and assault operations",
        olesBackstoryFinalBattleHeading: "On the Eve of the Final Battle (2030, Marinka):",
        olesBackstoryFinalBattleText: "By 2030, when Ukraine began its decisive offensive, Oles became one of the most experienced and valuable fighters. He held rank, the respect of commanders, and unofficial leadership among his peers. Pain, fatigue, and numerous scars were part of his essence, but his eyes burned with the same determination as at the beginning, only now deepened by the knowledge of the price of the struggle. He was in Marinka, on the front line of the Ukrainian offensive, ready for the final, decisive battle for Donbas. It was here, in this historical and symbolic place, that he was destined to face not only the last challenges of the war, but also the call of the thousand-year-old \"Volya\" of his ancestors, which is to manifest itself at a critical moment.",
        olesBackstoryBackButton: "← Back to main page",
        footerText: "&copy; 2025 Project \"VOLYA\". All rights reserved.",
    }
};
